In [7]:
import pandas as pd

In [68]:

import requests

API_KEY = 'AQVNwHYHkMWnOiKDh-gp-95vZs2yuwjtFE8rim_B'
FOLDER_ID = 'b1g7odg8qi4d1sdr8lpm'

url = 'https://searchapi.api.cloud.yandex.net/v2/wordstat/topRequests'
headers = {
    'Authorization': f'Api-Key {API_KEY}',
    'Content-Type': 'application/json',
}

payload = {
    'phrase': 'Яндекс вакансии',
    'devices': ['DEVICE_ALL'],
    'folderId': FOLDER_ID,
}

resp = requests.post(url, headers=headers, json=payload, timeout=30)
print(resp.status_code)
print(resp.text)
resp.raise_for_status()

data = resp.json()
for item in data.get('topRequests', []):
    print(item.get('phrase'), item.get('count'))

200
{
 "results": [
  {
   "phrase": "яндекс вакансии",
   "count": "82123"
  },
  {
   "phrase": "яндекс вакансии удаленно",
   "count": "12408"
  },
  {
   "phrase": "яндекс работа вакансии",
   "count": "11505"
  },
  {
   "phrase": "яндекс лавка вакансии",
   "count": "6784"
  },
  {
   "phrase": "яндекс маркет вакансии",
   "count": "6080"
  },
  {
   "phrase": "яндекс крауд вакансии",
   "count": "4727"
  },
  {
   "phrase": "яндекс дом вакансий",
   "count": "3401"
  },
  {
   "phrase": "яндекс вакансии москва",
   "count": "2935"
  },
  {
   "phrase": "яндекс вакансии удаленно на дому",
   "count": "2807"
  },
  {
   "phrase": "вакансии яндекс без опыта",
   "count": "2603"
  },
  {
   "phrase": "работа дома яндекс вакансии",
   "count": "2578"
  },
  {
   "phrase": "яндекс поддержка вакансии",
   "count": "2292"
  },
  {
   "phrase": "яндекс вакансии удаленно без опыта",
   "count": "2251"
  },
  {
   "phrase": "работа в яндекс удаленно вакансии",
   "count": "2222"
  },
  {
   "phrase": "яндекс вакансии без опыта работы",
   "count": "1959"
  },
  {
   "phrase": "яндекс курьер вакансии",
   "count": "1926"
  },
  {
   "phrase": "яндекс доставка вакансии",
   "count": "1868"
  },
  {
   "phrase": "яндекс еда вакансии",
   "count": "1841"
  },
  {
   "phrase": "яндекс такси вакансии",
   "count": "1678"
  },
  {
   "phrase": "яндекс вакансии спб",
   "count": "1606"
  },
  {
   "phrase": "яндекс склады вакансии",
   "count": "1376"
  },
  {
   "phrase": "вакансии яндекс удаленно на дому без опыта",
   "count": "1292"
  },
  {
   "phrase": "вакансии водитель яндекса",
   "count": "1183"
  },
  {
   "phrase": "вакансия яндекс сборщик",
   "count": "1155"
  },
  {
   "phrase": "яндекс работа на дому вакансии без опыта",
   "count": "1067"
  },
  {
   "phrase": "яндекс заказы вакансии",
   "count": "1036"
  },
  {
   "phrase": "яндекс крауд вакансии удаленно",
   "count": "1000"
  },
  {
   "phrase": "сборщик яндекс лавка вакансии",
   "count": "985"
  },
  {
   "phrase": "вакансии яндекс оператор",
   "count": "946"
  },
  {
   "phrase": "вакансия яндекс чаты",
   "count": "889"
  },
  {
   "phrase": "яндекс смена вакансии",
   "count": "869"
  },
  {
   "phrase": "яндекс вакансии подработка",
   "count": "868"
  },
  {
   "phrase": "яндекс самокаты вакансии",
   "count": "864"
  },
  {
   "phrase": "компания яндекс вакансии",
   "count": "860"
  },
  {
   "phrase": "яндекс маркет работа вакансии",
   "count": "825"
  },
  {
   "phrase": "работа яндекс крауд вакансии",
   "count": "806"
  },
  {
   "phrase": "яндекс сборщик заказов вакансии",
   "count": "805"
  },
  {
   "phrase": "яндекс крауд удаленная работа вакансии",
   "count": "796"
  },
  {
   "phrase": "яндекс бизнес вакансии",
   "count": "752"
  },
  {
   "phrase": "сайт вакансий яндекс",
   "count": "736"
  },
  {
   "phrase": "яндекс реклама вакансии",
   "count": "726"
  },
  {
   "phrase": "яндекс директ вакансии",
   "count": "723"
  },
  {
   "phrase": "работа в яндекс удаленно вакансии на дому",
   "count": "712"
  },
  {
   "phrase": "сборщик заказов яндекс лавка вакансии",
   "count": "688"
  },
  {
   "phrase": "яндекс пвз вакансии",
   "count": "683"
  },
  {
   "phrase": "яндекс драйв вакансии",
   "count": "673"
  },
  {
   "phrase": "яндекс вакансии отзывы",
   "count": "667"
  },
  {
   "phrase": "работа в яндексе удаленно вакансии без опыта",
   "count": "655"
  },
  {
   "phrase": "вакансия менеджера яндекс",
   "count": "653"
  },
  {
   "phrase": "яндекс смена подработка вакансии",
   "count": "626"
  }
 ],
 "associations": [
  {
   "phrase": "yandex com",
   "count": "58700"
  },
  {
   "phrase": "www yandex",
   "count": "123634"
  },
  {
   "phrase": "устроиться на работу",
   "count": "303207"
  },
  {
   "phrase": "а я пойду работать в понедельник",
   "count": "2334"
  },
  {
   "phrase": "www yandex com",
   "count": "3280"
  },
  {
   "phrase": "для работы телеграмма нужен",
   "count": "1970"
  },
  {
   "phrase": "на каких сайтах искать работу",
   "count": "2294"
  },
  {
   "phrase": "yandex услуги",
   "count": "1603"
  },
  {
   "phrase": "найти сотрудника на работу",
   "count": "2558"
  },
  {
   "phrase": "компания работа",
   "count": "208058"
  },
  {
   "phrase": "yandex search",
   "count": "91625"
  },
  {
   "phrase": "ъъ ру работа",
   "count": "160"
  },
  {
   "phrase": "yandex com tr",
   "count": "2077"
  },
  {
   "phrase": "yandex poisk",
   "count": "1829"
  },
  {
   "phrase": "куда устроиться на работу",
   "count": "16070"
  },
  {
   "phrase": "кхр ру работа",
   "count": "492"
  },
  {
   "phrase": "ххру поиск работы",
   "count": "295"
  },
  {
   "phrase": "yandex job",
   "count": "1072"
  },
  {
   "phrase": "шш ру работа",
   "count": "172"
  }
 ],
 "totalCount": "82123"
}

In [71]:
top_requests = data.get('results', [])
q_count = sum(int(result['count']) for result in top_requests)

In [72]:
q_count

181510

In [73]:
top_requests

[{'phrase': 'яндекс вакансии', 'count': '82123'},
 {'phrase': 'яндекс вакансии удаленно', 'count': '12408'},
 {'phrase': 'яндекс работа вакансии', 'count': '11505'},
 {'phrase': 'яндекс лавка вакансии', 'count': '6784'},
 {'phrase': 'яндекс маркет вакансии', 'count': '6080'},
 {'phrase': 'яндекс крауд вакансии', 'count': '4727'},
 {'phrase': 'яндекс дом вакансий', 'count': '3401'},
 {'phrase': 'яндекс вакансии москва', 'count': '2935'},
 {'phrase': 'яндекс вакансии удаленно на дому', 'count': '2807'},
 {'phrase': 'вакансии яндекс без опыта', 'count': '2603'},
 {'phrase': 'работа дома яндекс вакансии', 'count': '2578'},
 {'phrase': 'яндекс поддержка вакансии', 'count': '2292'},
 {'phrase': 'яндекс вакансии удаленно без опыта', 'count': '2251'},
 {'phrase': 'работа в яндекс удаленно вакансии', 'count': '2222'},
 {'phrase': 'яндекс вакансии без опыта работы', 'count': '1959'},
 {'phrase': 'яндекс курьер вакансии', 'count': '1926'},
 {'phrase': 'яндекс доставка вакансии', 'count': '1868'},
 {'phrase': 'яндекс еда вакансии', 'count': '1841'},
 {'phrase': 'яндекс такси вакансии', 'count': '1678'},
 {'phrase': 'яндекс вакансии спб', 'count': '1606'},
 {'phrase': 'яндекс склады вакансии', 'count': '1376'},
 {'phrase': 'вакансии яндекс удаленно на дому без опыта', 'count': '1292'},
 {'phrase': 'вакансии водитель яндекса', 'count': '1183'},
 {'phrase': 'вакансия яндекс сборщик', 'count': '1155'},
 {'phrase': 'яндекс работа на дому вакансии без опыта', 'count': '1067'},
 {'phrase': 'яндекс заказы вакансии', 'count': '1036'},
 {'phrase': 'яндекс крауд вакансии удаленно', 'count': '1000'},
 {'phrase': 'сборщик яндекс лавка вакансии', 'count': '985'},
 {'phrase': 'вакансии яндекс оператор', 'count': '946'},
 {'phrase': 'вакансия яндекс чаты', 'count': '889'},
 {'phrase': 'яндекс смена вакансии', 'count': '869'},
 {'phrase': 'яндекс вакансии подработка', 'count': '868'},
 {'phrase': 'яндекс самокаты вакансии', 'count': '864'},
 {'phrase': 'компания яндекс вакансии', 'count': '860'},
 {'phrase': 'яндекс маркет работа вакансии', 'count': '825'},
 {'phrase': 'работа яндекс крауд вакансии', 'count': '806'},
 {'phrase': 'яндекс сборщик заказов вакансии', 'count': '805'},
 {'phrase': 'яндекс крауд удаленная работа вакансии', 'count': '796'},
 {'phrase': 'яндекс бизнес вакансии', 'count': '752'},
 {'phrase': 'сайт вакансий яндекс', 'count': '736'},
 {'phrase': 'яндекс реклама вакансии', 'count': '726'},
 {'phrase': 'яндекс директ вакансии', 'count': '723'},
 {'phrase': 'работа в яндекс удаленно вакансии на дому', 'count': '712'},
 {'phrase': 'сборщик заказов яндекс лавка вакансии', 'count': '688'},
 {'phrase': 'яндекс пвз вакансии', 'count': '683'},
 {'phrase': 'яндекс драйв вакансии', 'count': '673'},
 {'phrase': 'яндекс вакансии отзывы', 'count': '667'},
 {'phrase': 'работа в яндексе удаленно вакансии без опыта', 'count': '655'},
 {'phrase': 'вакансия менеджера яндекс', 'count': '653'},
 {'phrase': 'яндекс смена подработка вакансии', 'count': '626'}]

Импортируем наш топ компаний

In [42]:
bigtech = pd.read_csv('bigtech_top (1).csv')
bigtech.company

0                           Yandex
1                           Т-Банк
2                      Wildberries
3                             Ozon
4     Ростелеком (цифровые активы)
                  ...
95                       Grow Food
96                         Flowwow
97                           Синто
98                             BSS
99                        Профи.ру
Name: company, Length: 100, dtype: object

Включают английские символы:

In [43]:

bigtech[bigtech.company.str.contains(r'[a-zA-Z]')]

,company,rating,market,revenue,growth,market_num
0,Yandex,1,"Экосистема, Social Networks, Edtech, Fintech, ...","1095,00","+109,9%",10
2,Wildberries,3,"Экосистема, E-com, TravelTech, Fintech","657,50 *","+107,3%",4
3,Ozon,4,"Экосистема, E-com, Traveltech, Fintech","615,70","+122,2%",4
8,VK,9,"Экосистема, Social Networks, Edtech, Fintech, ...","147,60","+50,9%",6
10,ГК Softline,11,IT-услуги,"120,64","+70,7%",1
12,Isource,13,"IT-услуги, E-com","108,33","+579,3%",2
13,Lamoda,14,E-com,"107,24","+74,9%",1
25,HH.ru,26,HRtech,"39,60",+120%,1
30,Sitronics Group,31,"IT-услуги, Transporttech","31,50","-16,1%",2
32,Positive Technologies,33,Cybersecurity,"24,50","+77,9%",1
38,Innostage,39,Cybersecurity,"18,60","+62,0%",1
39,IBS,40,IT-услуги,"18,13","+2,4%",1
40,Saby (Тензор),41,Business process automation,"17,40 *","+59,7%",1
45,Edna,46,Martech,"14,72","+63,9%",1
47,Whoosh,48,Sharing,"14,30",+124%,1
48,Tutu.ru,49,Traveltech,"14,00 *","+68,7%",1
51,Selectel,52,IT-услуги,"13,00 *","+57,3%",1
55,Axenix,56,IT-услуги,"12,40 *",+21%,1
56,SM lab,57,"IT-услуги, E-com","12,25 *","+421,0%",2
59,Skyeng,60,Edtech,"12,10 *","+27,4%",1
60,Carprice,61,"Classified, E-com","11,32","+34,8%",2
63,GlowByte,64,IT-услуги,"10,83","+28,8%",1
66,Solar staff,67,"Classified, Fintech","9,21","+30,6%",2
67,Astrum Entertainment,68,Gametech,"9,10","-28,1%",1
69,IT-One,70,IT-услуги,"8,76 *","+45,2%",1
70,UserGate,71,Cybersecurity,"8,73 *","+130,8%",1
71,Angara Security,72,Cybersecurity,"7,97","+73,9%",1
72,Litres (принадлежит Эксмо-АСТ),73,E-com,"7,75 *","+33,8%",1
75,CloudPayments + CloudTips + CloudKassir,76,Fintech,"7,25 *","+59,3%",1
77,Getcourse,78,Edtech,"6,79","+306,6%",1
80,Naumen,81,"IT-услуги, Business process automation, VoiceTech","6,70 *","+81,4%",3
81,VisorLabs,82,Cybersecurity,"6,62 *",+0%,1
86,Arenadata,87,IT-услуги,"6,00",+140%,1
87,Холдинг Performance Group,88,Foodtech,"5,45 *","+4,0%",1
93,BIA Technologies,94,"IT-услуги, Business process automation","4,57 *","+21,2%",2
94,BelkaCar,95,Sharing economy,"4,38","+1,3%",1
95,Grow Food,96,Foodtech,"4,30 *","+39,2%",1
96,Flowwow,97,Classified,"4,20 *","+225,8%",1
98,BSS,99,Fintech,"4,04","+49,5%",1

Только русские:

In [44]:
bigtech[bigtech.company.str.contains(r'^[а-яёА-ЯЁ]+$')]

,company,rating,market,revenue,growth,market_num
11,Авито,12,"E-Com, Classified","120,00 *","+86,3%",2
21,Айтеко,22,IT-услуги,"48,00","+55,4%",1
28,Газинформсервис,29,Cybersecurity,"33,33","+114,3%",1
29,Крок,30,IT-услуги,"32,00 *","+26,9%",1
31,Делимобиль,32,Sharing,"27,90",+86%,1
33,НВБС,34,IT-услуги,"23,95","+558,5%",1
34,Иви,35,VideoTech,"22,93","+80,0%",1
41,Эвотор,42,Fintech,"16,97","+47,6%",1
42,ИнфоТеКС,43,Cybersecurity,"16,44","+91,2%",1
44,Актион,45,Edtech,"15,00 *","+28,1%",1
50,ОТР,51,"IT-услуги, Fintech","13,34","+1,2%",2
52,ЦИАН,53,"Classified, Proptech","13,00",+0%,2
53,Синергия,54,Edtech,"12,73","+86,7%",1
58,УЦСБ,59,IT-услуги,"12,13","+126,7%",1
61,Диасофт,62,Fintech,"11,00 *","+53,0%",1
62,Сравни,63,"Fintech, Classified","11,00",+0%,2
64,АТОЛ,65,"IT-услуги, E-com","10,19","+78,4%",2
68,Сиссофт,69,IT-услуги,"8,94 *","+16,0%",1
74,ТерраЛинк,75,"IT-услуги, Business process automation","7,64","+54,3%",2
76,Амедиатека,77,Videotech,"6,87","+43,1%",1
78,Рексофт,79,IT-услуги,"6,77","+290,2%",1
79,Информзащита,80,Cybersecurity,"6,71 *","+2,3%",1
82,АСКОН,83,IT-услуги,"6,60","+73,7%",1
85,Юзтех,86,IT-услуги,"6,19","+52,2%",1
88,ЦКР,89,Business process automation,"5,41 *","+4,5%",1
90,Суточно,91,Traveltech,"5,37","+213,2%",1
91,Унитех,92,IT-услуги,"5,11 *","+44,7%",1
97,Синто,98,EnergyTech,"4,10 *","-22,6%",1

Только названия, включающие и русские и английские символы:

In [45]:
bigtech[bigtech.company.str.contains(r'[а-яёА-ЯЁ]') &
        bigtech.company.str.contains(r'[a-zA-Z]')]

,company,rating,market,revenue,growth,market_num
10,ГК Softline,11,IT-услуги,"120,64","+70,7%",1
40,Saby (Тензор),41,Business process automation,"17,40 *","+59,7%",1
72,Litres (принадлежит Эксмо-АСТ),73,E-com,"7,75 *","+33,8%",1
87,Холдинг Performance Group,88,Foodtech,"5,45 *","+4,0%",1

Содержат более одного слова (пробелы и /)

In [46]:
bigtech[bigtech.company.str.contains(r'[ / \\]')]

,company,rating,market,revenue,growth,market_num
4,Ростелеком (цифровые активы),5,"Экосистема, Telecom, Gametech, Edtech","341,40 *","+30,9%",4
5,Сбер (цифровые активы),6,"Экосистема, Fintech, Videotech, E-com, Transp...","283,30 *","+106,9%",9
6,ИТ-холдинг Т1,7,IT-услуги,"249,56","+69,4%",1
7,МТС (цифровые активы),8,"Экосистема, Telecom, Fintech, VideoTech","194,65 *","+118,0%",4
9,ИКС Холдинг (цифровые активы),10,IT-услуги,"140,00 *","+197,2%",1
10,ГК Softline,11,IT-услуги,"120,64","+70,7%",1
16,Лаборатория Касперского,17,Cybersecurity,"74,00 *","+43,7%",1
17,Концерн Телематика,18,"IT-услуги, Transporttech","65,00","+208,1%",2
18,Росатом (цифровые активы),19,IT-услуги,"60,00","+95,4%",1
19,ГК «ЛАНИТ»:,20,IT-услуги,"56,48 *","+102,3%",1
20,Точка банк,21,Fintech,"53,58","+180,2%",1
22,Группа Рубитех,23,"IT-услуги, ИТ-инфраструктура, Cybersecurity","44,60 *","+44,2%",3
23,ГК СКБ Контур,24,"IT-услуги, Business process automation","40,40","+53,0%",2
24,Лига Цифровой Экономики,25,IT-услуги,"40,00","+28,6%",1
26,Инфосистемы Джет,27,IT-услуги,"36,72","+43,2%",1
27,ГК Леста Игры,28,Gametech,"35,00","+821,1%",1
30,Sitronics Group,31,"IT-услуги, Transporttech","31,50","-16,1%",2
32,Positive Technologies,33,Cybersecurity,"24,50","+77,9%",1
35,ГК Базовые решения,36,IT-услуги,"21,95",+0%,1
37,Группа Астра,38,IT-услуги,"20,04","+212,3%",1
40,Saby (Тензор),41,Business process automation,"17,40 *","+59,7%",1
43,ВС Лаб,44,IT-услуги,"15,21 *","+91,1%",1
46,Первый Бит,47,"IT-услуги, Business process automation","14,51 *","+62,9%",2
49,Группа Консультант Плюс,50,Legaltech,"13,40","+11,6%",1
54,Код безопасности,55,Cybersecurity,"12,70 *","+71,6%",1
56,SM lab,57,"IT-услуги, E-com","12,25 *","+421,0%",2
65,ГК Урбантех,66,"IT-услуги, Transporttech","9,24","+37,3%",2
66,Solar staff,67,"Classified, Fintech","9,21","+30,6%",2
67,Astrum Entertainment,68,Gametech,"9,10","-28,1%",1
71,Angara Security,72,Cybersecurity,"7,97","+73,9%",1
72,Litres (принадлежит Эксмо-АСТ),73,E-com,"7,75 *","+33,8%",1
73,ГК Форс,74,"IT-услуги, Medtech","7,70 *","+25,4%",2
75,CloudPayments + CloudTips + CloudKassir,76,Fintech,"7,25 *","+59,3%",1
83,1520 Сигнал (входит в экосистему РЖД),84,TransportTech,"6,52 *","+63,4%",1
84,Форт Диалог,85,IT-услуги,"6,33 *","+108,9%",1
87,Холдинг Performance Group,88,Foodtech,"5,45 *","+4,0%",1
89,Сонет ИТ,90,IT-услуги,"5,40","+87,6%",1
92,Программный Продукт,93,IT-услуги,"4,87 *","+19,5%",1
93,BIA Technologies,94,"IT-услуги, Business process automation","4,57 *","+21,2%",2
95,Grow Food,96,Foodtech,"4,30 *","+39,2%",1

In [94]:
dict_rus_eng = {
    'Astrum Entertainment': 'аструм',
    'ИТ-холдинг Т1': 'т1',
    '1520 Сигнал (входит в экосистему РЖД)': 'ржд',
    'Лаборатория Касперского': 'касперский',
    'Ростелеком (цифровые активы)': 'ростелеком',
    'Сбер (цифровые активы)': 'сбер',
    'МТС (цифровые активы)': 'мтс',
    'Т-Банк': 'тбанк',
    'Yandex': 'яндекс',
    'Wildberries': 'вб',
    'Ozon': 'озон',
    'Edna': 'эдна',
    'Softline': 'софтлайн',
    'VK': 'вк',
    'Lamoda': 'ламода',
    'HH': 'хх',
    'Saby (Тензор)': 'тензор',
    'CloudPayments + CloudTips + CloudKassir': 'cloud',
    'Naumen': 'наумен',
    'VisorLabs': 'визорлабс',
    'Arenadata': 'аренадата',
    'Холдинг Performance Group': 'performance group',
    'BelkaCar': 'белка кар',
    'Getcourse': 'геткурс',
    'Grow Food': 'гроу фуд',
    'Litres (принадлежит Эксмо-АСТ)': 'литрес'
}

In [75]:
import re

def normalize_name(name):
  name = name.strip()
  name = re.sub(r'^гк\s+', '', name, flags=re.IGNORECASE)  # убрать ГК в начале - это влияет на запросы в вордстате
  name = re.sub(r'\s*\(цифровые активы\)\s*$', '', name, flags=re.IGNORECASE) #убираем в конце цифровые активы чтобы не портить статистику запросов
  return name.strip()

def get_value(name):
  cleaned_name = normalize_name(name)

  for k, v in dict_rus_eng.items():
    if normalize_name(k).lower() == cleaned_name.lower():
      return v
  return cleaned_name.lower()

bigtech['search_name'] = bigtech['company'].apply(get_value)

In [76]:
bigtech['search_name']

0         яндекс
1          тбанк
2             вб
3           озон
4     ростелеком
         ...
95      гроу фуд
96       flowwow
97         синто
98           bss
99      профи.ру
Name: search_name, Length: 100, dtype: object

In [77]:
bigtech['search_name'].dtypes

dtype('O')

In [78]:
import time
import requests

demand = [' вакансии', ' стажировка', ' собеседования', ' зп', ' зарплата'] #запросы которые будем испоьзовать для каждой компании

results = []

for name in bigtech['search_name']:
  row = {'company': name}
  total = 0

  for d in demand:
    phrase = name + d
    params = {
      'phrase': phrase,
      'devices': ['DEVICE_ALL'],
      'folderId': FOLDER_ID,
    }
    resp = requests.post(url, headers=headers, json=params, timeout=30)

    print(f"Запрос: {phrase}, статус: {resp.status_code}")
    if resp.status_code != 200:
        print(f"Ошибка: {resp.text}")
        continue
    data = resp.json()

    top_requests = data.get('results', [])
    q_count = sum(int(result['count']) for result in top_requests)

    row[d.strip()] = q_count
    row[d.strip() + '_top'] = top_requests

    total += q_count
    time.sleep(0.2)

  row['total'] = total
  results.append(row)

df = pd.DataFrame(results)
bdf = bigtech.copy()
df

Запрос: яндекс вакансии, статус: 200
Запрос: яндекс стажировка, статус: 200
Запрос: яндекс собеседования, статус: 200
Запрос: яндекс зп, статус: 200
Запрос: яндекс зарплата, статус: 200
Запрос: тбанк вакансии, статус: 200
Запрос: тбанк стажировка, статус: 200
Запрос: тбанк собеседования, статус: 200
Запрос: тбанк зп, статус: 200
Запрос: тбанк зарплата, статус: 200
Запрос: вб вакансии, статус: 200
Запрос: вб стажировка, статус: 200
Запрос: вб собеседования, статус: 200
Запрос: вб зп, статус: 200
Запрос: вб зарплата, статус: 200
Запрос: озон вакансии, статус: 200
Запрос: озон стажировка, статус: 200
Запрос: озон собеседования, статус: 200
Запрос: озон зп, статус: 200
Запрос: озон зарплата, статус: 200
Запрос: ростелеком вакансии, статус: 200
Запрос: ростелеком стажировка, статус: 200
Запрос: ростелеком собеседования, статус: 200
Запрос: ростелеком зп, статус: 200
Запрос: ростелеком зарплата, статус: 200
Запрос: сбер вакансии, статус: 200
Запрос: сбер стажировка, статус: 200
Запрос: сбер собеседования, статус: 200
Запрос: сбер зп, статус: 200
Запрос: сбер зарплата, статус: 200
Запрос: т1 вакансии, статус: 200
Запрос: т1 стажировка, статус: 200
Запрос: т1 собеседования, статус: 200
Запрос: т1 зп, статус: 200
Запрос: т1 зарплата, статус: 200
Запрос: мтс вакансии, статус: 200
Запрос: мтс стажировка, статус: 200
Запрос: мтс собеседования, статус: 200
Запрос: мтс зп, статус: 200
Запрос: мтс зарплата, статус: 200
Запрос: вк вакансии, статус: 200
Запрос: вк стажировка, статус: 200
Запрос: вк собеседования, статус: 200
Запрос: вк зп, статус: 200
Запрос: вк зарплата, статус: 200
Запрос: икс холдинг вакансии, статус: 200
Запрос: икс холдинг стажировка, статус: 200
Запрос: икс холдинг собеседования, статус: 200
Запрос: икс холдинг зп, статус: 200
Запрос: икс холдинг зарплата, статус: 200
Запрос: софтлайн вакансии, статус: 200
Запрос: софтлайн стажировка, статус: 200
Запрос: софтлайн собеседования, статус: 200
Запрос: софтлайн зп, статус: 200
Запрос: софтлайн зарплата, статус: 200
Запрос: авито вакансии, статус: 200
Запрос: авито стажировка, статус: 200
Запрос: авито собеседования, статус: 200
Запрос: авито зп, статус: 200
Запрос: авито зарплата, статус: 200
Запрос: isource вакансии, статус: 200
Запрос: isource стажировка, статус: 200
Запрос: isource собеседования, статус: 200
Запрос: isource зп, статус: 200
Запрос: isource зарплата, статус: 200
Запрос: ламода вакансии, статус: 200
Запрос: ламода стажировка, статус: 200
Запрос: ламода собеседования, статус: 200
Запрос: ламода зп, статус: 200
Запрос: ламода зарплата, статус: 200
Запрос: эр-телеком вакансии, статус: 200
Запрос: эр-телеком стажировка, статус: 200
Запрос: эр-телеком собеседования, статус: 200
Запрос: эр-телеком зп, статус: 200
Запрос: эр-телеком зарплата, статус: 200
Запрос: 1с вакансии, статус: 200
Запрос: 1с стажировка, статус: 200
Запрос: 1с собеседования, статус: 200
Запрос: 1с зп, статус: 200
Запрос: 1с зарплата, статус: 200
Запрос: касперский вакансии, статус: 200
Запрос: касперский стажировка, статус: 200
Запрос: касперский собеседования, статус: 200
Запрос: касперский зп, статус: 200
Запрос: касперский зарплата, статус: 200
Запрос: концерн телематика вакансии, статус: 200
Запрос: концерн телематика стажировка, статус: 200
Запрос: концерн телематика собеседования, статус: 200
Запрос: концерн телематика зп, статус: 200
Запрос: концерн телематика зарплата, статус: 200
Запрос: росатом вакансии, статус: 200
Запрос: росатом стажировка, статус: 200
Запрос: росатом собеседования, статус: 200
Запрос: росатом зп, статус: 200
Запрос: росатом зарплата, статус: 200
Запрос: «ланит»: вакансии, статус: 400
Ошибка: {
 "code": 3,
 "message": "Invalid query",
 "details": [
  {
   "@type": "type.googleapis.com/google.rpc.RequestInfo",
   "requestId": "71eda84c-235d-4d5c-8e9e-4375978d6c46"
  }
 ]
}

Запрос: «ланит»: стажировка, статус: 400
Ошибка: {
 "code": 3,
 "message": "Invalid query",
 "details": [
  {
   "@type": "type.googleapis.com/google.rpc.RequestInfo",
   "requestId": "fc58fb0e-7960-45bf-9af8-7d8aa3eaec0a"
  }
 ]
}

Запрос: «ланит»: собеседования, статус: 400
Ошибка: {
 "code": 3,
 "message": "Invalid query",
 "details": [
  {
   "@type": "type.googleapis.com/google.rpc.RequestInfo",
   "requestId": "3e5939b7-3b67-49fb-b944-7f24b1a5d758"
  }
 ]
}

Запрос: «ланит»: зп, статус: 400
Ошибка: {
 "code": 3,
 "message": "Invalid query",
 "details": [
  {
   "@type": "type.googleapis.com/google.rpc.RequestInfo",
   "requestId": "367511a5-b824-4ae8-a4e6-9a34d9842f3c"
  }
 ]
}

Запрос: «ланит»: зарплата, статус: 400
Ошибка: {
 "code": 3,
 "message": "Invalid query",
 "details": [
  {
   "@type": "type.googleapis.com/google.rpc.RequestInfo",
   "requestId": "58b0fed4-86e5-4220-be7c-6ac337b0dc4e"
  }
 ]
}

Запрос: точка банк вакансии, статус: 200
Запрос: точка банк стажировка, статус: 200
Запрос: точка банк собеседования, статус: 200
Запрос: точка банк зп, статус: 200
Запрос: точка банк зарплата, статус: 200
Запрос: айтеко вакансии, статус: 200
Запрос: айтеко стажировка, статус: 200
Запрос: айтеко собеседования, статус: 200
Запрос: айтеко зп, статус: 200
Запрос: айтеко зарплата, статус: 200
Запрос: группа рубитех вакансии, статус: 200
Запрос: группа рубитех стажировка, статус: 200
Запрос: группа рубитех собеседования, статус: 200
Запрос: группа рубитех зп, статус: 200
Запрос: группа рубитех зарплата, статус: 200
Запрос: скб контур вакансии, статус: 200
Запрос: скб контур стажировка, статус: 200
Запрос: скб контур собеседования, статус: 200
Запрос: скб контур зп, статус: 200
Запрос: скб контур зарплата, статус: 200
Запрос: лига цифровой экономики вакансии, статус: 200
Запрос: лига цифровой экономики стажировка, статус: 200
Запрос: лига цифровой экономики собеседования, статус: 200
Запрос: лига цифровой экономики зп, статус: 200
Запрос: лига цифровой экономики зарплата, статус: 200
Запрос: hh.ru вакансии, статус: 200
Запрос: hh.ru стажировка, статус: 200
Запрос: hh.ru собеседования, статус: 200
Запрос: hh.ru зп, статус: 200
Запрос: hh.ru зарплата, статус: 200
Запрос: инфосистемы джет вакансии, статус: 200
Запрос: инфосистемы джет стажировка, статус: 200
Запрос: инфосистемы джет собеседования, статус: 200
Запрос: инфосистемы джет зп, статус: 200
Запрос: инфосистемы джет зарплата, статус: 200
Запрос: леста игры вакансии, статус: 200
Запрос: леста игры стажировка, статус: 200
Запрос: леста игры собеседования, статус: 200
Запрос: леста игры зп, статус: 200
Запрос: леста игры зарплата, статус: 200
Запрос: газинформсервис вакансии, статус: 200
Запрос: газинформсервис стажировка, статус: 200
Запрос: газинформсервис собеседования, статус: 200
Запрос: газинформсервис зп, статус: 200
Запрос: газинформсервис зарплата, статус: 200
Запрос: крок вакансии, статус: 200
Запрос: крок стажировка, статус: 200
Запрос: крок собеседования, статус: 200
Запрос: крок зп, статус: 200
Запрос: крок зарплата, статус: 200
Запрос: sitronics group вакансии, статус: 200
Запрос: sitronics group стажировка, статус: 200
Запрос: sitronics group собеседования, статус: 200
Запрос: sitronics group зп, статус: 200
Запрос: sitronics group зарплата, статус: 200
Запрос: делимобиль вакансии, статус: 200
Запрос: делимобиль стажировка, статус: 200
Запрос: делимобиль собеседования, статус: 200
Запрос: делимобиль зп, статус: 200
Запрос: делимобиль зарплата, статус: 200
Запрос: positive technologies вакансии, статус: 200
Запрос: positive technologies стажировка, статус: 200
Запрос: positive technologies собеседования, статус: 200
Запрос: positive technologies зп, статус: 200
Запрос: positive technologies зарплата, статус: 200
Запрос: нвбс вакансии, статус: 200
Запрос: нвбс стажировка, статус: 200
Запрос: нвбс собеседования, статус: 200
Запрос: нвбс зп, статус: 200
Запрос: нвбс зарплата, статус: 200
Запрос: иви вакансии, статус: 200
Запрос: иви стажировка, статус: 200
Запрос: иви собеседования, статус: 200
Запрос: иви зп, статус: 200
Запрос: иви зарплата, статус: 200
Запрос: базовые решения вакансии, статус: 200
Запрос: базовые решения стажировка, статус: 200
Запрос: базовые решения собеседования, статус: 200
Запрос: базовые решения зп, статус: 200
Запрос: базовые решения зарплата, статус: 200
Запрос: к2тех вакансии, статус: 200
Запрос: к2тех стажировка, статус: 200
Запрос: к2тех собеседования, статус: 200
Запрос: к2тех зп, статус: 200
Запрос: к2тех зарплата, статус: 200
Запрос: группа астра вакансии, статус: 200
Запрос: группа астра стажировка, статус: 200
Запрос: группа астра собеседования, статус: 200
Запрос: группа астра зп, статус: 200
Запрос: группа астра зарплата, статус: 200
Запрос: innostage вакансии, статус: 200
Запрос: innostage стажировка, статус: 200
Запрос: innostage собеседования, статус: 200
Запрос: innostage зп, статус: 200
Запрос: innostage зарплата, статус: 200
Запрос: ibs вакансии, статус: 200
Запрос: ibs стажировка, статус: 200
Запрос: ibs собеседования, статус: 200
Запрос: ibs зп, статус: 200
Запрос: ibs зарплата, статус: 200
Запрос: тензор вакансии, статус: 200
Запрос: тензор стажировка, статус: 200
Запрос: тензор собеседования, статус: 200
Запрос: тензор зп, статус: 200
Запрос: тензор зарплата, статус: 200
Запрос: эвотор вакансии, статус: 200
Запрос: эвотор стажировка, статус: 200
Запрос: эвотор собеседования, статус: 200
Запрос: эвотор зп, статус: 200
Запрос: эвотор зарплата, статус: 200
Запрос: инфотекс вакансии, статус: 200
Запрос: инфотекс стажировка, статус: 200
Запрос: инфотекс собеседования, статус: 200
Запрос: инфотекс зп, статус: 200
Запрос: инфотекс зарплата, статус: 200
Запрос: вс лаб вакансии, статус: 200
Запрос: вс лаб стажировка, статус: 200
Запрос: вс лаб собеседования, статус: 200
Запрос: вс лаб зп, статус: 200
Запрос: вс лаб зарплата, статус: 200
Запрос: актион вакансии, статус: 200
Запрос: актион стажировка, статус: 200
Запрос: актион собеседования, статус: 200
Запрос: актион зп, статус: 200
Запрос: актион зарплата, статус: 200
Запрос: эдна вакансии, статус: 200
Запрос: эдна стажировка, статус: 200
Запрос: эдна собеседования, статус: 200
Запрос: эдна зп, статус: 200
Запрос: эдна зарплата, статус: 200
Запрос: первый бит вакансии, статус: 200
Запрос: первый бит стажировка, статус: 200
Запрос: первый бит собеседования, статус: 200
Запрос: первый бит зп, статус: 200
Запрос: первый бит зарплата, статус: 200
Запрос: whoosh вакансии, статус: 200
Запрос: whoosh стажировка, статус: 200
Запрос: whoosh собеседования, статус: 200
Запрос: whoosh зп, статус: 200
Запрос: whoosh зарплата, статус: 200
Запрос: tutu.ru вакансии, статус: 200
Запрос: tutu.ru стажировка, статус: 200
Запрос: tutu.ru собеседования, статус: 200
Запрос: tutu.ru зп, статус: 200
Запрос: tutu.ru зарплата, статус: 200
Запрос: группа консультант плюс вакансии, статус: 200
Запрос: группа консультант плюс стажировка, статус: 200
Запрос: группа консультант плюс собеседования, статус: 200
Запрос: группа консультант плюс зп, статус: 200
Запрос: группа консультант плюс зарплата, статус: 200
Запрос: отр вакансии, статус: 200
Запрос: отр стажировка, статус: 200
Запрос: отр собеседования, статус: 200
Запрос: отр зп, статус: 200
Запрос: отр зарплата, статус: 200
Запрос: selectel вакансии, статус: 200
Запрос: selectel стажировка, статус: 200
Запрос: selectel собеседования, статус: 200
Запрос: selectel зп, статус: 200
Запрос: selectel зарплата, статус: 200
Запрос: циан вакансии, статус: 200
Запрос: циан стажировка, статус: 200
Запрос: циан собеседования, статус: 200
Запрос: циан зп, статус: 200
Запрос: циан зарплата, статус: 200
Запрос: синергия вакансии, статус: 200
Запрос: синергия стажировка, статус: 200
Запрос: синергия собеседования, статус: 200
Запрос: синергия зп, статус: 200
Запрос: синергия зарплата, статус: 200
Запрос: код безопасности вакансии, статус: 200
Запрос: код безопасности стажировка, статус: 200
Запрос: код безопасности собеседования, статус: 200
Запрос: код безопасности зп, статус: 200
Запрос: код безопасности зарплата, статус: 200
Запрос: axenix вакансии, статус: 200
Запрос: axenix стажировка, статус: 200
Запрос: axenix собеседования, статус: 200
Запрос: axenix зп, статус: 200
Запрос: axenix зарплата, статус: 200
Запрос: sm lab вакансии, статус: 200
Запрос: sm lab стажировка, статус: 200
Запрос: sm lab собеседования, статус: 200
Запрос: sm lab зп, статус: 200
Запрос: sm lab зарплата, статус: 200
Запрос: банки.ру вакансии, статус: 200
Запрос: банки.ру стажировка, статус: 200
Запрос: банки.ру собеседования, статус: 200
Запрос: банки.ру зп, статус: 200
Запрос: банки.ру зарплата, статус: 200
Запрос: уцсб вакансии, статус: 200
Запрос: уцсб стажировка, статус: 200
Запрос: уцсб собеседования, статус: 200
Запрос: уцсб зп, статус: 200
Запрос: уцсб зарплата, статус: 200
Запрос: skyeng вакансии, статус: 200
Запрос: skyeng стажировка, статус: 200
Запрос: skyeng собеседования, статус: 200
Запрос: skyeng зп, статус: 200
Запрос: skyeng зарплата, статус: 200
Запрос: carprice вакансии, статус: 200
Запрос: carprice стажировка, статус: 200
Запрос: carprice собеседования, статус: 200
Запрос: carprice зп, статус: 200
Запрос: carprice зарплата, статус: 200
Запрос: диасофт вакансии, статус: 200
Запрос: диасофт стажировка, статус: 200
Запрос: диасофт собеседования, статус: 200
Запрос: диасофт зп, статус: 200
Запрос: диасофт зарплата, статус: 200
Запрос: сравни вакансии, статус: 200
Запрос: сравни стажировка, статус: 200
Запрос: сравни собеседования, статус: 200
Запрос: сравни зп, статус: 200
Запрос: сравни зарплата, статус: 200
Запрос: glowbyte вакансии, статус: 200
Запрос: glowbyte стажировка, статус: 200
Запрос: glowbyte собеседования, статус: 200
Запрос: glowbyte зп, статус: 200
Запрос: glowbyte зарплата, статус: 200
Запрос: атол вакансии, статус: 200
Запрос: атол стажировка, статус: 200
Запрос: атол собеседования, статус: 200
Запрос: атол зп, статус: 200
Запрос: атол зарплата, статус: 200
Запрос: урбантех вакансии, статус: 200
Запрос: урбантех стажировка, статус: 200
Запрос: урбантех собеседования, статус: 200
Запрос: урбантех зп, статус: 200
Запрос: урбантех зарплата, статус: 200
Запрос: solar staff вакансии, статус: 200
Запрос: solar staff стажировка, статус: 200
Запрос: solar staff собеседования, статус: 200
Запрос: solar staff зп, статус: 200
Запрос: solar staff зарплата, статус: 200
Запрос: аструм вакансии, статус: 200
Запрос: аструм стажировка, статус: 200
Запрос: аструм собеседования, статус: 200
Запрос: аструм зп, статус: 200
Запрос: аструм зарплата, статус: 200
Запрос: сиссофт вакансии, статус: 200
Запрос: сиссофт стажировка, статус: 200
Запрос: сиссофт собеседования, статус: 200
Запрос: сиссофт зп, статус: 200
Запрос: сиссофт зарплата, статус: 200
Запрос: it-one вакансии, статус: 200
Запрос: it-one стажировка, статус: 200
Запрос: it-one собеседования, статус: 200
Запрос: it-one зп, статус: 200
Запрос: it-one зарплата, статус: 200
Запрос: usergate вакансии, статус: 200
Запрос: usergate стажировка, статус: 200
Запрос: usergate собеседования, статус: 200
Запрос: usergate зп, статус: 200
Запрос: usergate зарплата, статус: 200
Запрос: angara security вакансии, статус: 200
Запрос: angara security стажировка, статус: 200
Запрос: angara security собеседования, статус: 200
Запрос: angara security зп, статус: 200
Запрос: angara security зарплата, статус: 200
Запрос: litres (принадлежит эксмо-аст) вакансии, статус: 200
Запрос: litres (принадлежит эксмо-аст) стажировка, статус: 200
Запрос: litres (принадлежит эксмо-аст) собеседования, статус: 200
Запрос: litres (принадлежит эксмо-аст) зп, статус: 200
Запрос: litres (принадлежит эксмо-аст) зарплата, статус: 200
Запрос: форс вакансии, статус: 200
Запрос: форс стажировка, статус: 200
Запрос: форс собеседования, статус: 200
Запрос: форс зп, статус: 200
Запрос: форс зарплата, статус: 200
Запрос: терралинк вакансии, статус: 200
Запрос: терралинк стажировка, статус: 200
Запрос: терралинк собеседования, статус: 200
Запрос: терралинк зп, статус: 200
Запрос: терралинк зарплата, статус: 200
Запрос: cloud вакансии, статус: 200
Запрос: cloud стажировка, статус: 200
Запрос: cloud собеседования, статус: 200
Запрос: cloud зп, статус: 200
Запрос: cloud зарплата, статус: 200
Запрос: амедиатека вакансии, статус: 200
Запрос: амедиатека стажировка, статус: 200
Запрос: амедиатека собеседования, статус: 200
Запрос: амедиатека зп, статус: 200
Запрос: амедиатека зарплата, статус: 200
Запрос: геткурс вакансии, статус: 200
Запрос: геткурс стажировка, статус: 200
Запрос: геткурс собеседования, статус: 200
Запрос: геткурс зп, статус: 200
Запрос: геткурс зарплата, статус: 200
Запрос: рексофт вакансии, статус: 200
Запрос: рексофт стажировка, статус: 200
Запрос: рексофт собеседования, статус: 200
Запрос: рексофт зп, статус: 200
Запрос: рексофт зарплата, статус: 200
Запрос: информзащита вакансии, статус: 200
Запрос: информзащита стажировка, статус: 200
Запрос: информзащита собеседования, статус: 200
Запрос: информзащита зп, статус: 200
Запрос: информзащита зарплата, статус: 200
Запрос: наумен вакансии, статус: 200
Запрос: наумен стажировка, статус: 200
Запрос: наумен собеседования, статус: 200
Запрос: наумен зп, статус: 200
Запрос: наумен зарплата, статус: 200
Запрос: визорлабс вакансии, статус: 200
Запрос: визорлабс стажировка, статус: 200
Запрос: визорлабс собеседования, статус: 200
Запрос: визорлабс зп, статус: 200
Запрос: визорлабс зарплата, статус: 200
Запрос: аскон вакансии, статус: 200
Запрос: аскон стажировка, статус: 200
Запрос: аскон собеседования, статус: 200
Запрос: аскон зп, статус: 200
Запрос: аскон зарплата, статус: 200
Запрос: ржд вакансии, статус: 200
Запрос: ржд стажировка, статус: 200
Запрос: ржд собеседования, статус: 200
Запрос: ржд зп, статус: 200
Запрос: ржд зарплата, статус: 200
Запрос: форт диалог вакансии, статус: 200
Запрос: форт диалог стажировка, статус: 200
Запрос: форт диалог собеседования, статус: 200
Запрос: форт диалог зп, статус: 200
Запрос: форт диалог зарплата, статус: 200
Запрос: юзтех вакансии, статус: 200
Запрос: юзтех стажировка, статус: 200
Запрос: юзтех собеседования, статус: 200
Запрос: юзтех зп, статус: 200
Запрос: юзтех зарплата, статус: 200
Запрос: аренадата вакансии, статус: 200
Запрос: аренадата стажировка, статус: 200
Запрос: аренадата собеседования, статус: 200
Запрос: аренадата зп, статус: 200
Запрос: аренадата зарплата, статус: 200
Запрос: performance group вакансии, статус: 200
Запрос: performance group стажировка, статус: 200
Запрос: performance group собеседования, статус: 200
Запрос: performance group зп, статус: 200
Запрос: performance group зарплата, статус: 200
Запрос: цкр вакансии, статус: 200
Запрос: цкр стажировка, статус: 200
Запрос: цкр собеседования, статус: 200
Запрос: цкр зп, статус: 200
Запрос: цкр зарплата, статус: 200
Запрос: сонет ит вакансии, статус: 200
Запрос: сонет ит стажировка, статус: 200
Запрос: сонет ит собеседования, статус: 200
Запрос: сонет ит зп, статус: 200
Запрос: сонет ит зарплата, статус: 200
Запрос: суточно вакансии, статус: 200
Запрос: суточно стажировка, статус: 200
Запрос: суточно собеседования, статус: 200
Запрос: суточно зп, статус: 200
Запрос: суточно зарплата, статус: 200
Запрос: унитех вакансии, статус: 200
Запрос: унитех стажировка, статус: 200
Запрос: унитех собеседования, статус: 200
Запрос: унитех зп, статус: 200
Запрос: унитех зарплата, статус: 200
Запрос: программный продукт вакансии, статус: 200
Запрос: программный продукт стажировка, статус: 200
Запрос: программный продукт собеседования, статус: 200
Запрос: программный продукт зп, статус: 200
Запрос: программный продукт зарплата, статус: 200
Запрос: bia technologies вакансии, статус: 200
Запрос: bia technologies стажировка, статус: 200
Запрос: bia technologies собеседования, статус: 200
Запрос: bia technologies зп, статус: 200
Запрос: bia technologies зарплата, статус: 200
Запрос: белка кар вакансии, статус: 200
Запрос: белка кар стажировка, статус: 200
Запрос: белка кар собеседования, статус: 200
Запрос: белка кар зп, статус: 200
Запрос: белка кар зарплата, статус: 200
Запрос: гроу фуд вакансии, статус: 200
Запрос: гроу фуд стажировка, статус: 200
Запрос: гроу фуд собеседования, статус: 200
Запрос: гроу фуд зп, статус: 200
Запрос: гроу фуд зарплата, статус: 200

,company,вакансии,вакансии_top,стажировка,стажировка_top,собеседования,собеседования_top,зп,зп_top,зарплата,зарплата_top,total
0,яндекс,181510.0,"[{'phrase': 'яндекс вакансии', 'count': '82123...",17302.0,"[{'phrase': 'яндекс стажировка', 'count': '124...",4423.0,"[{'phrase': 'собеседование в яндекс', 'count':...",7173.0,"[{'phrase': 'зп в яндексе', 'count': '1465'}, ...",21767.0,"[{'phrase': 'зарплаты в яндексе', 'count': '48...",232175
1,тбанк,10467.0,"[{'phrase': 'тбанк вакансии', 'count': '7724'}...",3506.0,"[{'phrase': 'тбанк стажировка', 'count': '3051...",273.0,"[{'phrase': 'собеседование тбанк', 'count': '2...",396.0,"[{'phrase': 'тбанк зп', 'count': '347'}, {'phr...",1122.0,"[{'phrase': 'тбанк зарплаты', 'count': '892'},...",15764
2,вб,32408.0,"[{'phrase': 'вб вакансии', 'count': '14879'}, ...",2956.0,"[{'phrase': 'вб стажировка', 'count': '1318'},...",130.0,"[{'phrase': 'собеседование на вб', 'count': '1...",6746.0,"[{'phrase': 'зп на вб', 'count': '2174'}, {'ph...",16786.0,"[{'phrase': 'зарплата на вб', 'count': '4808'}...",59026
3,озон,208544.0,"[{'phrase': 'озон вакансии', 'count': '89707'}...",5500.0,"[{'phrase': 'озон стажировка', 'count': '3835'...",1029.0,"[{'phrase': 'озон собеседование', 'count': '60...",10593.0,"[{'phrase': 'зп на озоне', 'count': '2795'}, {...",49235.0,"[{'phrase': 'озон зарплата', 'count': '19406'}...",274901
4,ростелеком,15048.0,"[{'phrase': 'ростелеком вакансии', 'count': '8...",577.0,"[{'phrase': 'ростелеком стажировка', 'count': ...",265.0,"[{'phrase': 'ростелеком собеседование', 'count...",101.0,"[{'phrase': 'зп в ростелекоме', 'count': '101'}]",1067.0,"[{'phrase': 'зарплата в ростелекоме', 'count':...",17058
...,...,...,...,...,...,...,...,...,...,...,...,...
95,гроу фуд,43.0,"[{'phrase': 'гроу фуд вакансии', 'count': '43'}]",0.0,[],0.0,[],0.0,[],0.0,[],43
96,flowwow,539.0,"[{'phrase': 'flowwow вакансии', 'count': '442'...",10.0,"[{'phrase': 'flowwow стажировка', 'count': '10'}]",0.0,[],0.0,[],0.0,[],549
97,синто,47.0,"[{'phrase': 'синто вакансии', 'count': '28'}, ...",0.0,[],0.0,[],0.0,[],0.0,[],47
98,bss,58.0,"[{'phrase': 'bss вакансии', 'count': '50'}, {'...",0.0,[],0.0,[],0.0,[],0.0,[],58
99,профи.ру,1175.0,"[{'phrase': 'профи ру вакансии', 'count': '835...",0.0,[],0.0,[],0.0,[],0.0,[],1175

In [80]:
bdf.head()

,company,rating,market,revenue,growth,market_num,search_name
0,Yandex,1,"Экосистема, Social Networks, Edtech, Fintech, ...","1095,00","+109,9%",10,яндекс
1,Т-Банк,2,"Экосистема, Fintech, TravelTech, Telecom, Edte...","962,00","+162,8%",6,тбанк
2,Wildberries,3,"Экосистема, E-com, TravelTech, Fintech","657,50 *","+107,3%",4,вб
3,Ozon,4,"Экосистема, E-com, Traveltech, Fintech","615,70","+122,2%",4,озон
4,Ростелеком (цифровые активы),5,"Экосистема, Telecom, Gametech, Edtech","341,40 *","+30,9%",4,ростелеком

In [81]:
merged = pd.merge(bdf, df, left_on='search_name', right_on='company', how='left', suffixes=('', '_df'))
merged.drop(columns='company_df', inplace=True)

merged[['вакансии', 'стажировка', 'собеседования', 'зп', 'зарплата', 'total']] = merged[['вакансии', 'стажировка', 'собеседования', 'зп', 'зарплата', 'total']].fillna(0).astype(int)

merged.head()

,company,rating,market,revenue,growth,market_num,search_name,вакансии,вакансии_top,стажировка,стажировка_top,собеседования,собеседования_top,зп,зп_top,зарплата,зарплата_top,total
0,Yandex,1,"Экосистема, Social Networks, Edtech, Fintech, ...","1095,00","+109,9%",10,яндекс,181510,"[{'phrase': 'яндекс вакансии', 'count': '82123...",17302,"[{'phrase': 'яндекс стажировка', 'count': '124...",4423,"[{'phrase': 'собеседование в яндекс', 'count':...",7173,"[{'phrase': 'зп в яндексе', 'count': '1465'}, ...",21767,"[{'phrase': 'зарплаты в яндексе', 'count': '48...",232175
1,Т-Банк,2,"Экосистема, Fintech, TravelTech, Telecom, Edte...","962,00","+162,8%",6,тбанк,10467,"[{'phrase': 'тбанк вакансии', 'count': '7724'}...",3506,"[{'phrase': 'тбанк стажировка', 'count': '3051...",273,"[{'phrase': 'собеседование тбанк', 'count': '2...",396,"[{'phrase': 'тбанк зп', 'count': '347'}, {'phr...",1122,"[{'phrase': 'тбанк зарплаты', 'count': '892'},...",15764
2,Wildberries,3,"Экосистема, E-com, TravelTech, Fintech","657,50 *","+107,3%",4,вб,32408,"[{'phrase': 'вб вакансии', 'count': '14879'}, ...",2956,"[{'phrase': 'вб стажировка', 'count': '1318'},...",130,"[{'phrase': 'собеседование на вб', 'count': '1...",6746,"[{'phrase': 'зп на вб', 'count': '2174'}, {'ph...",16786,"[{'phrase': 'зарплата на вб', 'count': '4808'}...",59026
3,Ozon,4,"Экосистема, E-com, Traveltech, Fintech","615,70","+122,2%",4,озон,208544,"[{'phrase': 'озон вакансии', 'count': '89707'}...",5500,"[{'phrase': 'озон стажировка', 'count': '3835'...",1029,"[{'phrase': 'озон собеседование', 'count': '60...",10593,"[{'phrase': 'зп на озоне', 'count': '2795'}, {...",49235,"[{'phrase': 'озон зарплата', 'count': '19406'}...",274901
4,Ростелеком (цифровые активы),5,"Экосистема, Telecom, Gametech, Edtech","341,40 *","+30,9%",4,ростелеком,15048,"[{'phrase': 'ростелеком вакансии', 'count': '8...",577,"[{'phrase': 'ростелеком стажировка', 'count': ...",265,"[{'phrase': 'ростелеком собеседование', 'count...",101,"[{'phrase': 'зп в ростелекоме', 'count': '101'}]",1067,"[{'phrase': 'зарплата в ростелекоме', 'count':...",17058

ЗП и зарплату можно объединить так как они создавались отдельно как запросы по причине простоты запросов пользователей (проверили в вордстате и зп гораздо чаще встречалось, решили и то и то учесть)

In [86]:
merged['зарплата_общая'] = merged['зп'] + merged['зарплата']

In [87]:
merged['зарплата_top_общий'] = merged['зп_top'] + merged['зарплата_top']

In [88]:
merged.drop(columns=['зп', 'зп_top', 'зарплата', 'зарплата_top'], inplace=True)

In [89]:
merged.head()

,company,rating,market,revenue,growth,market_num,search_name,вакансии,вакансии_top,стажировка,стажировка_top,собеседования,собеседования_top,total,зарплата_общая,зарплата_top_общий
0,Yandex,1,"Экосистема, Social Networks, Edtech, Fintech, ...","1095,00","+109,9%",10,яндекс,181510,"[{'phrase': 'яндекс вакансии', 'count': '82123...",17302,"[{'phrase': 'яндекс стажировка', 'count': '124...",4423,"[{'phrase': 'собеседование в яндекс', 'count':...",232175,28940,"[{'phrase': 'зп в яндексе', 'count': '1465'}, ..."
1,Т-Банк,2,"Экосистема, Fintech, TravelTech, Telecom, Edte...","962,00","+162,8%",6,тбанк,10467,"[{'phrase': 'тбанк вакансии', 'count': '7724'}...",3506,"[{'phrase': 'тбанк стажировка', 'count': '3051...",273,"[{'phrase': 'собеседование тбанк', 'count': '2...",15764,1518,"[{'phrase': 'тбанк зп', 'count': '347'}, {'phr..."
2,Wildberries,3,"Экосистема, E-com, TravelTech, Fintech","657,50 *","+107,3%",4,вб,32408,"[{'phrase': 'вб вакансии', 'count': '14879'}, ...",2956,"[{'phrase': 'вб стажировка', 'count': '1318'},...",130,"[{'phrase': 'собеседование на вб', 'count': '1...",59026,23532,"[{'phrase': 'зп на вб', 'count': '2174'}, {'ph..."
3,Ozon,4,"Экосистема, E-com, Traveltech, Fintech","615,70","+122,2%",4,озон,208544,"[{'phrase': 'озон вакансии', 'count': '89707'}...",5500,"[{'phrase': 'озон стажировка', 'count': '3835'...",1029,"[{'phrase': 'озон собеседование', 'count': '60...",274901,59828,"[{'phrase': 'зп на озоне', 'count': '2795'}, {..."
4,Ростелеком (цифровые активы),5,"Экосистема, Telecom, Gametech, Edtech","341,40 *","+30,9%",4,ростелеком,15048,"[{'phrase': 'ростелеком вакансии', 'count': '8...",577,"[{'phrase': 'ростелеком стажировка', 'count': ...",265,"[{'phrase': 'ростелеком собеседование', 'count...",17058,1168,"[{'phrase': 'зп в ростелекоме', 'count': '101'..."

In [95]:
merged[merged.вакансии_top.isna() == True]

,company,rating,market,revenue,growth,market_num,search_name,вакансии,вакансии_top,стажировка,стажировка_top,собеседования,собеседования_top,total,зарплата_общая,зарплата_top_общий
19,ГК «ЛАНИТ»:,20,IT-услуги,"56,48 *","+102,3%",1,«ланит»:,0,NaN,0,NaN,0,NaN,0,0,NaN

In [112]:
merged.loc[merged['search_name'] == '«ланит»:', 'search_name'] = 'ланит'

Ланит судя по всему не прошел до конца обработку названия - дополним вручную информацию по нему чтобы не тратить токены запросов прогоняя весь алгоритм заново

In [114]:
lanit_name = '«ланит»:'
lanit_query = 'ланит'

row = {'company': lanit_name}
total = 0

for d in demand:
  phrase = lanit_query + d
  params = {
      'phrase': phrase,
      'devices': ['DEVICE_ALL'],
      'folderId': FOLDER_ID,
  }

  resp = requests.post(url, headers=headers, json=params, timeout=30)

  print(f'Запрос: {phrase}, статус: {resp.status_code}')
  if resp.status_code != 200:
    print(f'Ошибка: {resp.text}')
    row[d.strip()] = 0
    row[d.strip() + '_top'] = []
    continue

  data = resp.json()
  top_requests = data.get('results', [])
  q_count = sum(int(result['count']) for result in top_requests)

  row[d.strip()] = q_count
  row[d.strip() + '_top'] = top_requests
  total += q_count

  time.sleep(0.2)

row['total'] = total

lanit_df = pd.DataFrame([row])
lanit_df

Запрос: ланит вакансии, статус: 200
Запрос: ланит стажировка, статус: 200
Запрос: ланит собеседования, статус: 200
Запрос: ланит зп, статус: 200
Запрос: ланит зарплата, статус: 200

,company,вакансии,вакансии_top,стажировка,стажировка_top,собеседования,собеседования_top,зп,зп_top,зарплата,зарплата_top,total
0,«ланит»:,1824,"[{'phrase': 'ланит вакансии', 'count': '789'},...",113,"[{'phrase': 'ланит стажировка', 'count': '113'}]",0,[],0,[],58,"[{'phrase': 'ланит зарплаты', 'count': '58'}]",1995

In [115]:
lanit_df['зарплата_общая'] = lanit_df['зп'] + lanit_df['зарплата']
lanit_df['зарплата_top_общий'] = lanit_df['зп_top'] + lanit_df['зарплата_top']

lanit_df.drop(columns=['зп', 'зп_top', 'зарплата', 'зарплата_top'], inplace=True)

lanit_df

,company,вакансии,вакансии_top,стажировка,стажировка_top,собеседования,собеседования_top,total,зарплата_общая,зарплата_top_общий
0,«ланит»:,1824,"[{'phrase': 'ланит вакансии', 'count': '789'},...",113,"[{'phrase': 'ланит стажировка', 'count': '113'}]",0,[],1995,58,"[{'phrase': 'ланит зарплаты', 'count': '58'}]"

In [116]:
mask = merged['search_name'] == 'ланит'

merged.loc[mask, 'вакансии'] = lanit_df.loc[0, 'вакансии']
merged.loc[mask, 'стажировка'] = lanit_df.loc[0, 'стажировка']
merged.loc[mask, 'собеседования'] = lanit_df.loc[0, 'собеседования']
merged.loc[mask, 'total'] = lanit_df.loc[0, 'total']
merged.loc[mask, 'зарплата_общая'] = lanit_df.loc[0, 'зарплата_общая']

In [118]:
merged.loc[mask, 'вакансии_top'] = pd.Series([lanit_df.loc[0, 'вакансии_top']], index=merged.index[mask])
merged.loc[mask, 'стажировка_top'] = pd.Series([lanit_df.loc[0, 'стажировка_top']], index=merged.index[mask])
merged.loc[mask, 'собеседования_top'] = pd.Series([lanit_df.loc[0, 'собеседования_top']], index=merged.index[mask])
merged.loc[mask, 'зарплата_top_общий'] = pd.Series([lanit_df.loc[0, 'зарплата_top_общий']], index=merged.index[mask])

In [119]:
merged[merged.search_name == 'ланит']

,company,rating,market,revenue,growth,market_num,search_name,вакансии,вакансии_top,стажировка,стажировка_top,собеседования,собеседования_top,total,зарплата_общая,зарплата_top_общий
19,ГК «ЛАНИТ»:,20,IT-услуги,"56,48 *","+102,3%",1,ланит,1824,"[{'phrase': 'ланит вакансии', 'count': '789'},...",113,"[{'phrase': 'ланит стажировка', 'count': '113'}]",0,[],1995,58.0,"[{'phrase': 'ланит зарплаты', 'count': '58'}]"

In [120]:
from google.colab import files

merged.to_csv('wordstat.csv', index=False)
files.download('wordstat.csv')