In [2]:
import pandas as pd

In [6]:
companies = pd.read_excel('final_dreamjob.xlsx')
companies.head()

,title,review,rec_share,review_cnts,review_name,emp_cnt,city,year_founded,industry,site,descr
0,"Амургазстрой, АОЗТ",NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Строительство, недвижимость, эксплуатация, про...",http://amurgazstroy.com,NaN
1,Ангар,NaN,NaN,NaN,NaN,NaN,Ульяновск,NaN,NaN,NaN,NaN
2,АРМ ГРУПП - Украина,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Строительство, недвижимость, эксплуатация, про...",http://newholland.ua,NaN
3,Арматек,NaN,NaN,NaN,NaN,NaN,Череповец,NaN,Товары народного потребления (непищевые),https://www.vst35.ru/,NaN
4,Армбудсервис,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Строительство, недвижимость, эксплуатация, про...",http://armbudservis.ibud.ua,NaN

In [7]:
videos = pd.read_csv('career_videos.csv')
videos.head()

,company_name,title,channel_title,video_type,description,video_category,published_at,duration,subscriber_count,view_count,like_count,days_from_publication,interest_score,tags,video_url
0,Yandex,Ты все еще хочешь работать в Яндекс?,Антон Назаров I Осознанная Меркантильность,shorts,Узнаем подробности работы в Яндексе от жоского...,Education,2025-05-19T06:14:07Z,PT59S,52100,258468,2525,325,9.962168e+06,"['осознанная меркантильность', 'антон назаров'...",https://youtu.be/We8bzlF1e2k
1,Yandex,"Говорят, что в Яндексе мало платят. Это правда...",Яндекс,shorts,NaN,Science & Technology,2023-08-05T08:35:52Z,PT55S,474000,94269,1395,978,2.674206e+04,[],https://youtu.be/CuQ0iqA0vsI
2,Yandex,Кого я НИКОГДА не возьму в Яндекс? #работа #пс...,Irina Panfilova,shorts,"🚀 Хотите построить карьеру в IT, но не знаете,...",People & Blogs,2025-07-01T21:00:54Z,PT25S,1350,4573,10,281,5.512674e+02,"['карьера it', 'карьера', 'it', 'it компания',...",https://youtu.be/ljHUMWtCqEY
3,Yandex,Школа разработки от Яндекс #IT #работа,Не сидится,shorts,@necdtsa - полный выпуск на канале!,Science & Technology,2023-05-29T16:49:15Z,PT10S,1260,1130,9,1045,8.727956e+00,[],https://youtu.be/DHlhJdY_VPM
4,Yandex,🤑 Сколько стажёрам платят в Яндексе?,Яндекс,shorts,NaN,Science & Technology,2023-09-29T11:31:38Z,PT36S,474000,52961,551,922,3.536346e+03,[],https://youtu.be/5o8U5FPnj54

In [8]:
companies.shape

(20202, 11)

In [9]:
videos.shape

(2725, 15)

In [10]:
videos.company_name.unique()

array(['Yandex', 'Т-Банк', 'Wildberries', 'Ozon',
       'Ростелеком (цифровые активы)', 'Сбер (цифровые активы)',
       'ИТ-холдинг Т1', 'МТС (цифровые активы)', 'VK',
       'ИКС Холдинг (цифровые активы)', 'ГК Softline', 'Авито', 'Isource',
       'Lamoda', 'ЭР-Телеком', '1С', 'Лаборатория Касперского',
       'Концерн Телематика', 'Росатом (цифровые активы)', 'ГК «ЛАНИТ»:',
       'Точка банк', 'Айтеко', 'Группа Рубитех', 'ГК СКБ Контур',
       'Лига Цифровой Экономики', 'HH.ru', 'Инфосистемы Джет',
       'ГК Леста Игры', 'Газинформсервис', 'Крок', 'Sitronics Group',
       'Делимобиль', 'Positive Technologies', 'К2Тех', 'Tutu.ru'],
      dtype=object)

Функция для чистки названий компании:

In [14]:
import re

def norm(x):
    if pd.isna(x):
        return None
    x = str(x).lower().strip()
    x = re.sub(r'["'']', '', x)
    x = re.sub(r'[()\\[\\],.:;]', ' ', x)
    x = re.sub(r'[-_/]', ' ', x)
    x = re.sub(r'\s+', ' ', x).strip()
    return x

Функция для создания доп столбца в companies для объединения с videos

In [19]:
brand_aliases = {
    'Yandex': ['яндекс', 'yandex'],
    'Т-Банк': ['т банк', 'тинькофф', 't bank', 'tinkoff'],
    'Wildberries': ['wildberries', 'вайлдберриз'],
    'Ozon': ['ozon', 'озон'],
    'Ростелеком (цифровые активы)': ['ростелеком'],
    'Сбер (цифровые активы)': ['сбер', 'сбербанк'],
    'ИТ-холдинг Т1': ['т1', 'ит холдинг т1', 't1'],
    'МТС (цифровые активы)': ['мтс', 'mts'],
    'VK': ['vk', 'вк', 'mail ru', 'mailru', 'вконтакте'],
    'ИКС Холдинг (цифровые активы)': ['икс холдинг', 'x holding'],
    'ГК Softline': ['softline', 'софтлайн'],
    'Авито': ['авито', 'avito'],
    'Isource': ['isource'],
    'Lamoda': ['lamoda', 'ламода'],
    'ЭР-Телеком': ['эр телеком', 'эр телеком холдинг', 'dom ru', 'дом ру'],
    '1С': ['1с', '1 c', '1c'],
    'Лаборатория Касперского': ['лаборатория касперского', 'касперский', 'kaspersky'],
    'Концерн Телематика': ['концерн телематика', 'телематика'],
    'Росатом (цифровые активы)': ['росатом'],
    'ГК «ЛАНИТ»:': ['ланит', 'lanit'],
    'Точка банк': ['точка', 'банк точка', 'tochka'],
    'Айтеко': ['айтеко', 'iteco'],
    'Группа Рубитех': ['рубитех'],
    'ГК СКБ Контур': ['скб контур', 'контур', 'skb kontur'],
    'Лига Цифровой Экономики': ['лига цифровой экономики'],
    'HH.ru': ['hh', 'hh ru', 'headhunter', 'хедхантер'],
    'Инфосистемы Джет': ['инфосистемы джет', 'джет'],
    'ГК Леста Игры': ['леста', 'lesta', 'леста игры'],
    'Газинформсервис': ['газинформсервис'],
    'Крок': ['крок', 'croc'],
    'Sitronics Group': ['sitronics', 'ситроникс', 'sitronics group'],
    'Делимобиль': ['делимобиль', 'delimobil'],
    'Positive Technologies': ['positive technologies', 'positive', 'позитив', 'позитив технолоджиз'],
    'К2Тех': ['к2тех', 'к2 тех', 'k2tech', 'k2 tech'],
    'Tutu.ru': ['tutu', 'tutu ru', 'туту']
}

def map_brand(title_norm):
    if pd.isna(title_norm):
        return None

    for brand, aliases in brand_aliases.items():
        for alias in aliases:
            if alias in title_norm:
                return brand
    return None

In [20]:
c = companies.copy()
v = videos.copy()

#Создаем нормализованные тайтлы с двух сторон - videos и companies
c['title_norm'] = c['title'].apply(norm)
v['company_norm'] = v['company_name'].apply(norm)

#Создаем в companies доп столбец для того чтобы смерджить ее с videos
c['company_name'] = c['title_norm'].apply(map_brand)


c['company_name'].notna().sum()

np.int64(246)

Посмотрим на те строки, которые получилось смерджить по названию с videos:

In [21]:
matched = c[c['company_name'].notna()]
matched

,title,review,rec_share,review_cnts,review_name,emp_cnt,city,year_founded,industry,site,descr,title_norm,company_name
53,Вертикаль МАТТЕХПОСТАВКА.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Строительство, недвижимость, эксплуатация, про...",http://vertikal.kharkov.ua,NaN,вертикаль маттехпоставка.,VK
197,Микроклимат-ЛТД,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Строительство, недвижимость, эксплуатация, про...",http://microklimat.com.ua,NaN,микроклимат лтд,Крок
342,Точка Росы,NaN,NaN,NaN,NaN,NaN,Владимир,NaN,NaN,http://tochkarosi33.ru,NaN,точка росы,Точка банк
407,Юго-Восток-Поставка,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Строительство, недвижимость, эксплуатация, про...",http://skdonbass.com.ru,NaN,юго восток поставка,VK
569,Микроком Сич,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Телекоммуникации, связь",http://microcom.net.ua,NaN,микроком сич,Крок
...,...,...,...,...,...,...,...,...,...,...,...,...,...
19982,ТелеПорт Банк,"4,4",86%,7.0,Очень хорошо,NaN,Москва,NaN,Финансовый сектор,http://www.mti-bank.ru,NaN,телепорт банк,Т-Банк
19992,МТС Банк,"4,0",76%,1238.0,Очень хорошо,1000-9999,Москва,1993.0,Финансовый сектор,http://www.mtsbank.ru,МТС Банк – цифровой банк экосистемы МТС. Мы за...,мтс банк,МТС (цифровые активы)
20019,Муниципальное бюджетное учреждение Центральная...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Управление многопрофильными активами,http://crbnry.my1.ru,NaN,муниципальное бюджетное учреждение центральная...,Инфосистемы Джет
20020,Муниципальное бюджетное учреждение Центр молод...,NaN,NaN,2.0,NaN,NaN,Саратов,NaN,NaN,Перейти,NaN,муниципальное бюджетное учреждение центр молод...,Инфосистемы Джет
20123,НаПоправку,"4,5",87%,69.0,Очень хорошо,100-499,Санкт-Петербург,2014.0,"Информационные технологии, системная интеграци...",https://spb.napopravku.ru,NaN,напоправку,VK

Видно, что точка росы стала вдруг Точка банком
НаПоправку стал ВК
надо это пофиксить с помощью регулярных выражений

In [24]:
c['title_norm'] = c['title'].apply(norm)

brand_patterns = {
    'Yandex': [r'\bяндекс\w*\b', r'\byandex\b'],
    'Т-Банк': [r'\bтинькофф\w*\b', r'\bт\s*банк\b', r'\bt\s*bank\b'],
    'Wildberries': [r'\bwildberries\b', r'\bвайлдберриз\b'],
    'Ozon': [r'\bozon\b', r'\bозон\b'],
    'Ростелеком (цифровые активы)': [r'\bростелеком\w*\b'],
    'Сбер (цифровые активы)': [r'\bсбер\w*\b', r'\bсбербанк\w*\b'],
    'ИТ-холдинг Т1': [r'\bт1\b', r'\bt1\b'],
    'МТС (цифровые активы)': [r'\bмтс\b', r'\bmts\b'],
    'VK': [r'\bvk\b', r'\bвк\b', r'\bвконтакте\b', r'\bmail ru\b', r'\bmailru\b'],
    'ИКС Холдинг (цифровые активы)': [r'\bикс холдинг\b', r'\bx holding\b'],
    'ГК Softline': [r'\bsoftline\b', r'\bсофтлайн\b'],
    'Авито': [r'\bавито\b', r'\bavito\b'],
    'Isource': [r'\bisource\b'],
    'Lamoda': [r'\blamoda\b', r'\bламода\b'],
    'ЭР-Телеком': [r'\bэр телеком\b', r'\bэртелеком\b', r'\bдом ру\b', r'\bdom ru\b'],
    '1С': [r'\b1с\b', r'\b1c\b'],
    'Лаборатория Касперского': [r'\bлаборатория касперского\b', r'\bкасперск\w*\b', r'\bkaspersky\b'],
    'Концерн Телематика': [r'\bконцерн телематика\b', r'\bтелематика\b'],
    'Росатом (цифровые активы)': [r'\bросатом\w*\b'],
    'ГК «ЛАНИТ»:': [r'\bланит\b', r'\blanit\b'],
    'Точка банк': [r'\bточка банк\b', r'\bбанк точка\b', r'\btochka bank\b'],
    'Айтеко': [r'\bайтеко\b', r'\biteco\b'],
    'Группа Рубитех': [r'\bрубитех\b'],
    'ГК СКБ Контур': [r'\bскб контур\b', r'\bконтур\b', r'\bskb kontur\b'],
    'Лига Цифровой Экономики': [r'\bлига цифровой экономики\b'],
    'HH.ru': [r'\bhh ru\b', r'\bhh\b', r'\bheadhunter\b', r'\bхедхантер\b'],
    'Инфосистемы Джет': [r'\bинфосистемы джет\b', r'\bджет\b'],
    'ГК Леста Игры': [r'\bлеста игры\b', r'\bлеста\b', r'\blesta\b'],
    'Газинформсервис': [r'\bгазинформсервис\b'],
    'Крок': [r'\bкрок\b', r'\bcroc\b'],
    'Sitronics Group': [r'\bsitronics\b', r'\bситроникс\w*\b'],
    'Делимобиль': [r'\bделимобиль\b', r'\bdelimobil\b'],
    'Positive Technologies': [r'\bpositive technologies\b', r'\bpositive\b', r'\bпозитив\w*\b'],
    'К2Тех': [r'\bк2тех\b', r'\bк2 тех\b', r'\bk2tech\b', r'\bk2 tech\b'],
    'Tutu.ru': [r'\btutu ru\b', r'\btutu\b', r'\bтуту\b'],
}

def map_brand(title_norm):
    if pd.isna(title_norm):
        return None

    for brand, patterns in brand_aliases.items():
        for pattern in patterns:
            if re.search(pattern, title_norm):
                return brand
    return None



c['company_name'] = c['title_norm'].apply(map_brand)
c['company_name'].notna().sum()

np.int64(68)

In [25]:
matched_new = c[c['company_name'].notna()]
matched_new

,title,review,rec_share,review_cnts,review_name,emp_cnt,city,year_founded,industry,site,descr,title_norm,company_name
2275,Ozon,"4,5",93%,11034.0,Очень хорошо,более 10000,Москва,1998.0,"Информационные технологии, системная интеграци...",https://job.ozon.ru/,Ozon - быстрорастущая e-commerce платформа с р...,ozon,Ozon
2284,Лаборатория Касперского,"4,3",88%,671.0,Очень хорошо,1000-9999,Москва,1997.0,"Информационные технологии, системная интеграци...",https://kaspersky.ru,"Мы верим, что в будущем технологии улучшат жиз...",лаборатория касперского,Лаборатория Касперского
2295,Госкорпорация Росатом,"3,8",77%,742.0,Хорошо,более 10000,Россия,NaN,Государственные организации,http://www.rosatom.ru,NaN,госкорпорация росатом,Росатом (цифровые активы)
2304,Авито,"4,2",80%,1031.0,Очень хорошо,более 10000,Россия,2007.0,"Информационные технологии, системная интеграци...",http://www.avito.ru,Авито — самый посещаемый сервис объявлений в м...,авито,Авито
2317,ИНЖИНИРИНГОВЫЙ ДИВИЗИОН ГОСКОРПОРАЦИИ РОСАТОМ,"3,8",78%,538.0,Хорошо,более 10000,Нижний Новгород,NaN,"Строительство, недвижимость, эксплуатация, про...",http://ase-ec.ru,NaN,инжиниринговый дивизион госкорпорации росатом,Росатом (цифровые активы)
...,...,...,...,...,...,...,...,...,...,...,...,...,...
18170,Корпоративная Академия Росатома,"3,7",67%,48.0,Хорошо,100-499,Москва,2012.0,Образовательные учреждения,http://www.rosatom-academy.ru,NaN,корпоративная академия росатома,Росатом (цифровые активы)
18203,Корпорация Телематика - Лидер,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Сельское хозяйство,http://agrogps.ru,NaN,корпорация телематика лидер,Концерн Телематика
18263,КПК Центральная сберкасса,NaN,NaN,NaN,NaN,NaN,Казань,NaN,Финансовый сектор,http://центральнаясберкасса.рф,NaN,кпк центральная сберкасса,Сбер (цифровые активы)
18384,КРОК,"4,2",80%,634.0,Очень хорошо,1000-9999,Москва,1992.0,"Информационные технологии, системная интеграци...",http://www.croc.ru,КРОК — драйвер развития ИТ-отрасли с момента о...,крок,Крок
19992,МТС Банк,"4,0",76%,1238.0,Очень хорошо,1000-9999,Москва,1993.0,Финансовый сектор,http://www.mtsbank.ru,МТС Банк – цифровой банк экосистемы МТС. Мы за...,мтс банк,МТС (цифровые активы)

Теперь такой проблемы не наблюдается - видно, что количество совпавших тайтлов из companies снизилось

In [27]:
df_merge_companies = c.merge(
    v,
    on='company_name',
    how='left',
    suffixes=('_company', '_video')
)

df_merge_companies.head()

,title_company,review,rec_share,review_cnts,review_name,emp_cnt,city,year_founded,industry,site,...,published_at,duration,subscriber_count,view_count,like_count,days_from_publication,interest_score,tags,video_url,company_norm
0,"Амургазстрой, АОЗТ",NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Строительство, недвижимость, эксплуатация, про...",http://amurgazstroy.com,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Ангар,NaN,NaN,NaN,NaN,NaN,Ульяновск,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,АРМ ГРУПП - Украина,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Строительство, недвижимость, эксплуатация, про...",http://newholland.ua,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Арматек,NaN,NaN,NaN,NaN,NaN,Череповец,NaN,Товары народного потребления (непищевые),https://www.vst35.ru/,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Армбудсервис,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Строительство, недвижимость, эксплуатация, про...",http://armbudservis.ibud.ua,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [30]:
df_merge_all = c.merge(
    v,
    on='company_name',
    how='outer',
    suffixes=('_company', '_video')
)

df_merge_all.head()

,title_company,review,rec_share,review_cnts,review_name,emp_cnt,city,year_founded,industry,site,...,published_at,duration,subscriber_count,view_count,like_count,days_from_publication,interest_score,tags,video_url,company_norm
0,1С:ВДГБ,"4,2",74%,38.0,Очень хорошо,меньше 100,Россия,NaN,"Информационные технологии, системная интеграци...",http://www.vdgb.ru,...,2025-05-11T07:06:50Z,PT11M51S,4560.0,17022.0,667.0,333.0,127273.483239,[],https://youtu.be/txQvwiDMV8A,1с
1,1С:ВДГБ,"4,2",74%,38.0,Очень хорошо,меньше 100,Россия,NaN,"Информационные технологии, системная интеграци...",http://www.vdgb.ru,...,2025-04-05T21:00:32Z,PT19M1S,7000.0,15987.0,507.0,368.0,50303.250653,"['1с', '1с программирование', 'программист 1с ...",https://youtu.be/ZwJbSQzk-R4,1с
2,1С:ВДГБ,"4,2",74%,38.0,Очень хорошо,меньше 100,Россия,NaN,"Информационные технологии, системная интеграци...",http://www.vdgb.ru,...,2026-02-13T17:26:16Z,PT21M30S,3910.0,11091.0,375.0,54.0,218475.207801,"['Учет', 'Учетник', 'Бизнес', 'Налоги', 'Прогр...",https://youtu.be/DU44P2xevCk,1с
3,1С:ВДГБ,"4,2",74%,38.0,Очень хорошо,меньше 100,Россия,NaN,"Информационные технологии, системная интеграци...",http://www.vdgb.ru,...,2025-10-24T15:01:21Z,PT5M27S,275.0,10117.0,178.0,166.0,54241.746988,[],https://youtu.be/dhVSpeyGOS4,1с
4,1С:ВДГБ,"4,2",74%,38.0,Очень хорошо,меньше 100,Россия,NaN,"Информационные технологии, системная интеграци...",http://www.vdgb.ru,...,2025-08-02T19:54:04Z,PT21M28S,1220.0,11417.0,346.0,249.0,79322.931727,"['1С', '1С обучение', '1С программирование', '...",https://youtu.be/u8RPBXz8_ns,1с

In [31]:
video_stats = pd.DataFrame(v['company_name'].value_counts()).reset_index()
video_stats.columns = ['company_name', 'video_count']

matched_companies = set(c['company_name'].dropna().unique())

video_stats['matched'] = video_stats['company_name'].isin(matched_companies)
video_stats[video_stats['matched'] == False]

       company_name  video_count  matched
19  Sitronics Group           81    False
20       Точка банк           79    False
22    ГК Леста Игры           68    False
25          Isource           60    False
26       Делимобиль           60    False
31   Группа Рубитех           55    False
33          Tutu.ru           20    False
34            К2Тех            2    False

Остались компании, которые не попали в итоговый смердженный датасет

Судя по просмотренным в экселе значениям этих компаний и правда нет в данных, собранных с DreamJob. В таком случае сделаем отдельный мердж с помощью right join чтобы не потерять данные компании

In [34]:
df_content = c.merge(
    v,
    on="company_name",
    how="right",
    suffixes=("_company", "_video")
)

df_content.head()

,title_company,review,rec_share,review_cnts,review_name,emp_cnt,city,year_founded,industry,site,...,published_at,duration,subscriber_count,view_count,like_count,days_from_publication,interest_score,tags,video_url,company_norm
0,Яндекс Крауд,"4,2",79%,3471.0,Очень хорошо,более 10000,Москва,2005.0,NaN,https://crowd.yandex.ru/,...,2025-05-19T06:14:07Z,PT59S,52100,258468,2525,325,9.962168e+06,"['осознанная меркантильность', 'антон назаров'...",https://youtu.be/We8bzlF1e2k,yandex
1,Яндекс,"4,2",78%,4189.0,Очень хорошо,более 10000,Москва,1997.0,"Информационные технологии, системная интеграци...",https://yandex.ru/jobs/,...,2025-05-19T06:14:07Z,PT59S,52100,258468,2525,325,9.962168e+06,"['осознанная меркантильность', 'антон назаров'...",https://youtu.be/We8bzlF1e2k,yandex
2,Яндекс Команда для бизнеса,"4,5",93%,6911.0,Очень хорошо,более 10000,Москва,NaN,NaN,NaN,...,2025-05-19T06:14:07Z,PT59S,52100,258468,2525,325,9.962168e+06,"['осознанная меркантильность', 'антон назаров'...",https://youtu.be/We8bzlF1e2k,yandex
3,Яндекс,"4,2",78%,4189.0,Очень хорошо,более 10000,Москва,1997.0,"Информационные технологии, системная интеграци...",https://yandex.ru/jobs/,...,2025-05-19T06:14:07Z,PT59S,52100,258468,2525,325,9.962168e+06,"['осознанная меркантильность', 'антон назаров'...",https://youtu.be/We8bzlF1e2k,yandex
4,Яндекс Крауд,"4,2",79%,3471.0,Очень хорошо,более 10000,Москва,2005.0,NaN,https://crowd.yandex.ru/,...,2023-08-05T08:35:52Z,PT55S,474000,94269,1395,978,2.674206e+04,[],https://youtu.be/CuQ0iqA0vsI,yandex

Посмотрим что есть в итоге:

In [35]:
df_merge_companies.shape

(26000, 28)

In [36]:
df_merge_all.shape

(26425, 28)

In [37]:
df_content.shape

(6291, 28)

##Итого:

Получилось два датафрейма:
- общий (full outer join)
- общий смердженный для компаний (left join)
- общий смердженный для контента (right join)


Дополним все это еще данными из [списка топа бигтех компаний из исследования](https://smartranking.ru/ru/ranking/big-tech/#:~:text=Table_title:%20%D0%A0%D0%B5%D0%B9%D1%82%D0%B8%D0%BD%D0%B3%20%D0%BA%D1%80%D1%83%D0%BF%D0%BD%D0%B5%D0%B9%D1%88%D0%B8%D1%85%20%D1%82%D0%B5%D1%85%D0%BD%D0%BE%D0%BB%D0%BE%D0%B3%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D1%85%20%D0%BA%D0%BE%D0%BC%D0%BF%D0%B0%D0%BD%D0%B8%D0%B9%20BigTech%20100,%D1%81%D0%B5%D1%80%D0%B2%D0%B8%D1%81%D1%8B%20%D0%BE%D1%82%20Ozon%20%D0%91%D0%B0%D0%BD%D0%BA%2C%20Ozon%20Travel.%20%7C) - его мы спарсили в прроцессе работы с Youtube API и он использовался в отборе компаний для сбора контента.

In [80]:
bigtech = pd.read_csv('bigtech_top (1).csv')
bigtech.head()

,company,rating,market,revenue,growth,market_num
0,Yandex,1,"Экосистема, Social Networks, Edtech, Fintech, ...","1095,00","+109,9%",10
1,Т-Банк,2,"Экосистема, Fintech, TravelTech, Telecom, Edte...","962,00","+162,8%",6
2,Wildberries,3,"Экосистема, E-com, TravelTech, Fintech","657,50 *","+107,3%",4
3,Ozon,4,"Экосистема, E-com, Traveltech, Fintech","615,70","+122,2%",4
4,Ростелеком (цифровые активы),5,"Экосистема, Telecom, Gametech, Edtech","341,40 *","+30,9%",4

##Компании

In [81]:
bigtech['company_norm'] = bigtech['company'].apply(norm)

df_comp_final = df_merge_companies.merge(
    bigtech,
    left_on='company_norm',
    right_on='company_norm',
    how='left',
    suffixes=('_company', '_top')
)

In [82]:
df_comp_final

,title_company,review,rec_share,review_cnts,review_name,emp_cnt,city,year_founded,industry,site,...,interest_score,tags,video_url,company_norm,company,rating,market,revenue,growth,market_num
0,"Амургазстрой, АОЗТ",NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Строительство, недвижимость, эксплуатация, про...",http://amurgazstroy.com,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Ангар,NaN,NaN,NaN,NaN,NaN,Ульяновск,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,АРМ ГРУПП - Украина,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Строительство, недвижимость, эксплуатация, про...",http://newholland.ua,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Арматек,NaN,NaN,NaN,NaN,NaN,Череповец,NaN,Товары народного потребления (непищевые),https://www.vst35.ru/,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Армбудсервис,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Строительство, недвижимость, эксплуатация, про...",http://armbudservis.ibud.ua,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25995,Национальный инвестиционный альянс,NaN,NaN,NaN,NaN,NaN,Москва,NaN,"Строительство, недвижимость, эксплуатация, про...",http://russiainvest.ru,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25996,Национальный институт гуманитарной и психологи...,NaN,NaN,NaN,NaN,NaN,Москва,NaN,Образовательные учреждения,http://www.nigpil.ru,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25997,Национальный исследовательский Томский государ...,"3,7",68%,19.0,Хорошо,1000-9999,Томск,1878.0,Образовательные учреждения,http://www.tsu.ru/,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25998,Национальный исследовательский Томский политех...,"3,6",73%,150.0,Хорошо,1000-9999,Томск,NaN,Образовательные учреждения,http://tpu.ru,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25999,Национальный исследовательский университет Выс...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Управление многопрофильными активами,http://hse.ru,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [85]:
bigtech.loc[
    ~bigtech['company_norm'].isin(df_merge_companies['company_norm']),
    ['company', 'company_norm']
]

            company     company_norm
12          Isource          isource
20       Точка банк       точка банк
22   Группа Рубитех   группа рубитех
27    ГК Леста Игры    гк леста игры
30  Sitronics Group  sitronics group
..              ...              ...
95        Grow Food        grow food
96          Flowwow          flowwow
97            Синто            синто
98              BSS              bss
99         Профи.ру         профи.ру

[73 rows x 2 columns]

## Контент

In [91]:
df_content_final = df_content.merge(
    bigtech,
    left_on='company_norm',
    right_on='company_norm',
    how='left',
    suffixes=('_company', '_top')
)
df_content_final

,title_company,review,rec_share,review_cnts,review_name,emp_cnt,city,year_founded,industry,site,...,interest_score,tags,video_url,company_norm,company,rating,market,revenue,growth,market_num
0,Яндекс Крауд,"4,2",79%,3471.0,Очень хорошо,более 10000,Москва,2005.0,NaN,https://crowd.yandex.ru/,...,9.962168e+06,"['осознанная меркантильность', 'антон назаров'...",https://youtu.be/We8bzlF1e2k,yandex,Yandex,1,"Экосистема, Social Networks, Edtech, Fintech, ...","1095,00","+109,9%",10
1,Яндекс,"4,2",78%,4189.0,Очень хорошо,более 10000,Москва,1997.0,"Информационные технологии, системная интеграци...",https://yandex.ru/jobs/,...,9.962168e+06,"['осознанная меркантильность', 'антон назаров'...",https://youtu.be/We8bzlF1e2k,yandex,Yandex,1,"Экосистема, Social Networks, Edtech, Fintech, ...","1095,00","+109,9%",10
2,Яндекс Команда для бизнеса,"4,5",93%,6911.0,Очень хорошо,более 10000,Москва,NaN,NaN,NaN,...,9.962168e+06,"['осознанная меркантильность', 'антон назаров'...",https://youtu.be/We8bzlF1e2k,yandex,Yandex,1,"Экосистема, Social Networks, Edtech, Fintech, ...","1095,00","+109,9%",10
3,Яндекс,"4,2",78%,4189.0,Очень хорошо,более 10000,Москва,1997.0,"Информационные технологии, системная интеграци...",https://yandex.ru/jobs/,...,9.962168e+06,"['осознанная меркантильность', 'антон назаров'...",https://youtu.be/We8bzlF1e2k,yandex,Yandex,1,"Экосистема, Social Networks, Edtech, Fintech, ...","1095,00","+109,9%",10
4,Яндекс Крауд,"4,2",79%,3471.0,Очень хорошо,более 10000,Москва,2005.0,NaN,https://crowd.yandex.ru/,...,2.674206e+04,[],https://youtu.be/CuQ0iqA0vsI,yandex,Yandex,1,"Экосистема, Social Networks, Edtech, Fintech, ...","1095,00","+109,9%",10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6286,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.934926e+07,"['путешествие', 'путешествия', 'россия', 'прир...",https://youtu.be/_R8mDUATWUM,tutu.ru,Tutu.ru,49,Traveltech,"14,00 *","+68,7%",1
6287,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.558669e+04,"['трум трум', 'шортс', 'балерина капучино', 'к...",https://youtu.be/2cLAiqlV9p4,tutu.ru,Tutu.ru,49,Traveltech,"14,00 *","+68,7%",1
6288,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.281150e+13,"['pinkfong', 'family', 'kids', 'children', 'to...",https://youtu.be/0FXw3ezmly0,tutu.ru,Tutu.ru,49,Traveltech,"14,00 *","+68,7%",1
6289,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.572394e+08,"['роблокс мемы', 'роблокс мемы тик ток', 'робл...",https://youtu.be/lMuEB3D--H0,tutu.ru,Tutu.ru,49,Traveltech,"14,00 *","+68,7%",1
6290,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.496137e+08,[],https://youtu.be/rcZxPRlGT40,tutu.ru,Tutu.ru,49,Traveltech,"14,00 *","+68,7%",1

##Все

In [92]:
df_all_final = df_merge_all.merge(
    bigtech,
    left_on='company_norm',
    right_on='company_norm',
    how='left',
    suffixes=('_company', '_top')
)
df_all_final

,title_company,review,rec_share,review_cnts,review_name,emp_cnt,city,year_founded,industry,site,...,interest_score,tags,video_url,company_norm,company,rating,market,revenue,growth,market_num
0,1С:ВДГБ,"4,2",74%,38.0,Очень хорошо,меньше 100,Россия,NaN,"Информационные технологии, системная интеграци...",http://www.vdgb.ru,...,127273.483239,[],https://youtu.be/txQvwiDMV8A,1с,1С,16.0,IT-услуги,"75,00 *","+15,6%",1.0
1,1С:ВДГБ,"4,2",74%,38.0,Очень хорошо,меньше 100,Россия,NaN,"Информационные технологии, системная интеграци...",http://www.vdgb.ru,...,50303.250653,"['1с', '1с программирование', 'программист 1с ...",https://youtu.be/ZwJbSQzk-R4,1с,1С,16.0,IT-услуги,"75,00 *","+15,6%",1.0
2,1С:ВДГБ,"4,2",74%,38.0,Очень хорошо,меньше 100,Россия,NaN,"Информационные технологии, системная интеграци...",http://www.vdgb.ru,...,218475.207801,"['Учет', 'Учетник', 'Бизнес', 'Налоги', 'Прогр...",https://youtu.be/DU44P2xevCk,1с,1С,16.0,IT-услуги,"75,00 *","+15,6%",1.0
3,1С:ВДГБ,"4,2",74%,38.0,Очень хорошо,меньше 100,Россия,NaN,"Информационные технологии, системная интеграци...",http://www.vdgb.ru,...,54241.746988,[],https://youtu.be/dhVSpeyGOS4,1с,1С,16.0,IT-услуги,"75,00 *","+15,6%",1.0
4,1С:ВДГБ,"4,2",74%,38.0,Очень хорошо,меньше 100,Россия,NaN,"Информационные технологии, системная интеграци...",http://www.vdgb.ru,...,79322.931727,"['1С', '1С обучение', '1С программирование', '...",https://youtu.be/u8RPBXz8_ns,1с,1С,16.0,IT-услуги,"75,00 *","+15,6%",1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26420,Национальный инвестиционный альянс,NaN,NaN,NaN,NaN,NaN,Москва,NaN,"Строительство, недвижимость, эксплуатация, про...",http://russiainvest.ru,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26421,Национальный институт гуманитарной и психологи...,NaN,NaN,NaN,NaN,NaN,Москва,NaN,Образовательные учреждения,http://www.nigpil.ru,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26422,Национальный исследовательский Томский государ...,"3,7",68%,19.0,Хорошо,1000-9999,Томск,1878.0,Образовательные учреждения,http://www.tsu.ru/,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26423,Национальный исследовательский Томский политех...,"3,6",73%,150.0,Хорошо,1000-9999,Томск,NaN,Образовательные учреждения,http://tpu.ru,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26424,Национальный исследовательский университет Выс...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Управление многопрофильными активами,http://hse.ru,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [93]:
from google.colab import files

bigtech.to_csv('bigtech_top.csv', index=False)

df_all_final.to_csv('df_all_final.csv', index=False)
df_content_final.to_csv('df_videos_final.csv', index=False)
df_comp_final.to_csv('df_companies_final.csv', index=False)


files.download('df_all_final.csv')
files.download('df_videos_final.csv')
files.download('df_companies_final.csv')